### ISSUE TITLE
Use endpoint descriptions to generate the routes

### ISSUE THREAD

**Issue by adamw** [Bunyod/scala-seed-bb.g8#9]
The endpoints described in https://github.com/Bunyod/akka-http-tapir.g8/blob/master/src/main/g8/$seedName$/src/main/scala/$package__packaged$/domain/spec/TemplateEndpoints.scala (currently only used for documentation, as far as I understand), could also be used to generate the routes, currently in: https://github.com/Bunyod/akka-http-tapir.g8/blob/master/src/main/g8/%24seedName%24/src/main/scala/%24package__packaged%24/http/template/%24className%3Bformat%3D%22Camel%22%24Routes.scala

This would reduce duplication of the specification

**Comment by Bunyod** [comment]
Thanks for your suggestion. I could reduce duplication of the specification. But It brokes my tests. I need to take another approach to write tests for routes

**Comment by Bunyod** [comment]
fixed with PR #11 & #10
